arch: dinov2 # options: dino, dinov2, dinov3, resnet50

model_type: small_reg

dataset: CUB2011 # \in [CUB2011, StanfordCars]

# custom folder name for storing files
# no custom folder if none
custom_folder: null

# Log_dir for storing files
# if specified this will replace the full path
# of the log_dir
# if none it will be created automatically
# specify if you want to continue running a specific job
# folder must be in tmp/<arch>/<dataset>
log_dir: null

sweep_log_dir: null

# Specify whether to finetune after dense training or not
ft: True

# retrain specifies whether finetuning
# should be repeated even though the finetuned model exists
retrain: False

# options are sgd, adamw_schedulefree and sgd_schedulefree for now
optimizer: adamw_schedulefree

# Parameters related to the data coming from dino
data:

  # img_size of the input image
  # doesnt change input data
  # so dont change it
  img_size: 224

  # patch size of dino
  # changing it wont do anything so just leave it like that
  patch_size: 14

  # whether to use NormLayer 
  # for feature maps and feature vectors
  # from Dino
  use_norm: True

  # loader norm is a normalization
  # of the maps coming from the loader
  loader_norm: False

  # type of feature map to be used
  # options: 0, 1
  # number stands for number of layers
  # from the last layer
  layer_num: 0

  rerun_data_gen: False # whether to rerun the data generation or not

  # Randomly turning off patches 
  # in input data
  dropout: 0 # default 0.1

  # method used to generate the masks
  mask_gen_method: collect_attn_recall

  # number of dilations applied to the generated masks
  # to increase recall of target object
  n_dilations: 2

# Parameters related to the model
# which uses the data coming from dino
model:
  # Channels to map feat_channels onto
  n_features: 512

  hidden_size: 2048

  residual: False

  # when linear: layers and activations need to be specified
  # when transformer: ... need to be specified
  # arch \in [linear, transformer]
  arch: linear

  # Layers of the model
  # the first layer must have 
  # feat_channels as input; 
  # the last layer must have 
  # n_features as output
  # excluded are activations and other normalizing functions
  # they obviously dont need fixed sizes
  n_layers: 4

  use_batch_norm: True

  activation: relu

  use_dropout: False

  # Scale feature vector
  scale_feat_vec: False

  # Apply relu after scaling feature vector
  relu_after_scaling: False

  # Architecture of the model
  # either normal or concat
  # normal only has an effect when feat_vec_type is avg_pooling
  # takes feat_map and averages it to feat_vec
  # concat takes feat_map and feat_vec and concatenates them
  # and then averages them to feat_vec
  arch_type: normal # options: normal, concat

  # type of feature vector to be used
  # options: normal, avg_pooling, max_pooling
  # avg_pooling means average pooling
  # means taking the average pooling from 
  # the feature map as the feature vector
  feat_vec_type: avg_pooling # options: normal, avg_pooling, max_pooling, mean_avg_pooling

  # what to use a mask for the feature map
  # to filter foreground object (object of interest)
  masking: null # options: segmentations, dino, learn_masking, null

  use_pre_concat_mask: False
  use_post_concat_mask: False
  
# Parameters related to the training
# of the dense model
dense:
  # params means hyperparameters like batch_size, epochs; loss means beta and gamma

  # Dense Training Params
  epochs: 40 # 25
  weight_decay: 0.0007
  batch_size: 32 # originally for batch_norm=True equal to 32
  start_lr: 0.001
  # Dropout for FinalLayer in dense Training
  dropout: 0.2 # default 0.3 with bacth_norm=True

  # only relevant if using some sort of
  # sgd implementation
  momentum: 0.9

  # Only relevant if no schedulefree
  # optimizer is used
  step_lr: 10
  step_lr_decay: 0.04

  # gamma for the fsl - feature similarity loss
  fsl: 0

  # beta for the fdl
  fdl: 0.5 # 1 

  pdl: 0

  # Uses fdl but always with average of feature maps as feature vector
  beta_avg: 0

  # L1 Loss for Feature Maps to make problem
  # better solvable for QPM
  # 1.0e-10 is basically 0 -> no loss; will be ignored in training
  # 1.0e-10 because yaml isnt able to read 1e-10
  l1_fm_weight: 0
  l1_w_weight: 0

  l1_fv_weight: 0 # 5
  norm_with_max: True

  rpl_weight: 0

  random_noise: 0 # default 0.1

# Parameters related to the finetuning
finetune:
  # Parameters related to the model
  # optimizing for interpretability
  model_type: qsenn # choices: ["qsenn","sldd","qpm"]
  # Mode, no_b, no_r only relevant for qpm
  # no_b and no_r only relevant for iterative mode
  mode: iterative
  no_b: True
  no_r: False
  n_features: 50 # 50
  n_per_class: 5 # 5

  # time_limit and mip_gap 
  # are only used for qpm
  mip_gap: 5.0e-3 # not in percent; default 1e-4
  time_limit: 10800 # default 10800

  # params means hyperparameters like batch_size, epochs; loss means beta and gamma

  # Finetune Training Params
  epochs: 50
  start_lr: 0.005
  weight_decay: 0.0008
  batch_size: 16

  # droupout for final layer in finetune Training
  dropout: 0

  # only relevant if using some sort of
  # sgd implementation
  momentum: 0.95

  # Only relevant if no
  # schedulefree learning rate is used
  step_lr: 10
  step_lr_decay: 0.04

  # gamma for the fsl - feature similarity loss
  fsl: 0

  # beta for the fdl
  fdl: 1

  pdl: 0

  # Related to Conservation of Similarity Loss
  cofs_weight: 0 # 5

  cofs_k: 32

  per_prototype: False

  # Uses fdl but always with average of feature maps as feature vector
  beta_avg: 0

  # L1 Loss for Feature Maps to make problem
  # better solvable for QPM
  l1_fm_weight: 5

  l1_w_weight: 0

  l1_fv_weight: 0 # 1
  norm_with_max: False

  rpl_weight: 0

  grounding_loss_weight: 0 # 5

  random_noise: 0 # 0.1

  # Specify to train last n epochs without crossentropy loss
  ce_free_epochs: 0 # 10

# settings related to the feature diversity loss
loss:
  # whether to use a mask for the fdl
  mask_type: null # options: segmentations, null